### ISSUE TITLE
Running Acceptance Tests, Error

### ISSUE THREAD

**Issue by followalongs** [jorgeacetozi/notepad#9]
Hi 

I know the book is a couple of years old but I am following along with the identified versions of libraries, docker images etc.. but I have hit a problem; can anyone help? 

I'm on the Notepad App chapter, Section on running acceptance tests, after I have started the Selenium grid and run the first acceptance test I receive the following exception. any pointers? 

Standalone unit test and Integration tests all pass. 

ERROR org.thymeleaf.TemplateEngine - [THYMELEAF][http-nio-8080-exec-5] Exception processing template "index": Can't find bundle for base name org.apache.xerces.impl.msg.XMLMessages, locale en_GB
Exception in thread "http-nio-8080-exec-5" java.lang.NoClassDefFoundError: ch/qos/logback/classic/spi/ThrowableProxy
        at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:119)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.log(Logger.java:765)
        at org.slf4j.bridge.SLF4JBridgeHandler.callLocationAwareLogger(SLF4JBridgeHandler.java:221)
        at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:303)
        at java.util.logging.Logger.log(Logger.java:738)
        at java.util.logging.Logger.doLog(Logger.java:765)
        at java.util.logging.Logger.logp(Logger.java:1042)
        at org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:181)
        at org.apache.juli.logging.DirectJDKLog.error(DirectJDKLog.java:147)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1472)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by fgonzalemx** [comment]
Hi, followalongs.
I am also reading this book. I had the same problem and after many days of searching on internet I founded a solution:
Move templates dir from src/main/resources/templates/ to /resources/templates/. (same level with src)
